apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-demonset
  labels:
    k8s-app: nginx-demonset
spec:
  selector:
    matchLabels:
      name: nginx-demonset-pod
  template:
    metadata:
      labels:
        name: nginx-demonset-pod
    spec:
      containers:
      - name: nginx-demonset-container
        image: nginx

