apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment1
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: sql-container
          image: mysql
          envFrom: # to set entire env variables from the secret.
            - secretRef:
                name: mysqlcreds
          ports:
            - containerPort: 3306
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-deployment1-np-service
spec:
  type: NodePort
  selector:
    # app.kubernetes.io/name: mysql
    app: mysql
  ports:
    - port: 82
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 3306
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30006
