#nginx-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    env: # Setting Environment Variables
      - name: SECRET_VAR1 # Env variable Name
        valueFrom:
          secretKeyRef:
            name: mysecretname # secret name; kubectl get secrets.
            key: mysecretkey1 # key in that secret file.
      - name: SECRET_VAR2
        valueFrom:
          secretKeyRef:
            name: mysecretname
            key: mysecretkey2

# key: to get the key use:
  
# kubectl describe secrets mysecretname ( or ) kubectl edit secrets mysecretname -o yaml 

# under Data we can find the key:value pairs. This key is the key we should use in key: mysecretkey


