#nginx-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: mysecret
      mountPath: /mysecretdirectory # Directory to be created inside container
      readOnly: true
  volumes:
  - name: mysecretvol # Volume Name
    secret: 
      secretName: mysecretname # Secret Name 