apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # no of pods
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 3306
              protocol: TCP 
          volumeMounts:
           - name: myvolume
             mountPath: "/etc/myk8svolume" # if directory is present it will use it or will be created
      volumes: 
      - name: myvolume
        hostPath: 
          path: /etc/k8scontainerdata  # if directory is present it will use it or will be created on WORKER NODE.


#single container single vloume
