apiVersion: v1
kind: Service
metadata:
  name: myloadbalancer
  namespace: test
spec:
  type: LoadBalancer
  selector: 
    app: myapp
  ports:
    - port: 81         # can be any port
      targetPort: 80   # zoncoffee image port 

#generates a load balancer service

# kubeclt get svc -n test

# lbname:port (here 81)

