apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: amazon-deployment-vpa
  namespace: suryans
spec:
  targetRef:
    kind: Deployment
    name: amazon-deployment
    apiVersion: apps/v1
  updatePolicy:
   updateMode: "Off"


# STEP 1: clone the git repository.

# git clone https://github.com/kubernetes/autoscaler.git

# STEP 2: run the shell script.

# cd ./autoscaler/hack/vpa-up.sh 

# STEP 3: then deploy the VerticalPodAutoscaler 
