apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # no of pods
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 3306
              protocol: TCP 
          volumeMounts:
          - name: myvolume # Volume to be attached.
            mountPath: "/newdirectory" # directory to be created in container
            # readOnly: true 
      volumes: 
      - name: myvolume # Vol name
        configMap: 
          name: myconfmap1 # CM name

# This will apply the entire ConfigMap into our POD.